# Week 1 - Pandas Series

## Pre-Class 9/29/26

- a series is basically a fancy list/array where theres a customizeable index

In [ ]:
# Load packages
import pandas as pd
import numpy as np

In [3]:
s = pd.Series([1, 2, 999, 999], index = ['A', 'B', 'C', 'D'])

check-in exercise 1:

In [ ]:
# Replace all values greater than equal to 999 with NaN
s.mask(s >= 999)

A    1.0
B    2.0
C    NaN
D    NaN
dtype: float64

In [5]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [6]:
# Change index
df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

check in exercise 2:

In [ ]:
# Change col names
df.columns = ['c1', 'c2']
df

   c1   c2
a   0  3.1
b   1  3.2
c   2  3.3

### Summary

- series are like the building blocks or atoms of pandas
- a df is a library of series
- series are lists but u can customize the index
- series methods are most often applied to a column of a df